### ISSUE TITLE
admin666

### ISSUE THREAD

**Issue by V1og** [yzddmr6/WebCrack#1]
爆破提示 admin  admin666 成功 但登陆提示报错密码错误  和其他返回长度一样

**Comment by yzddmr6** [comment]
是用的现成的cms还是个人开发的？
如果是cms麻烦提供一下名字跟版本
如果是个人开发的可以抓特征值配置json文件

**Comment by V1og** [comment]
> 是用的现成的cms还是个人开发的？
> 如果是cms麻烦提供一下名字跟版本
> 如果是个人开发的可以抓特征值配置json文件

应该是集成的  但是CMS指纹查询不到 jiuzhou888.net/?admin/Login.php

**Comment by yzddmr6** [comment]
新版已修复
