### ISSUE TITLE
这个项目还能使用吗？为什么我扫描的时候没有任何显示

### ISSUE THREAD

**Issue by cs81** [yzddmr6/WebCrack#10]
![image](https://user-images.githubusercontent.com/52037441/102441341-0716c100-405d-11eb-8b1c-4f35594b5746.png)

**Comment by cs81** [comment]
root@kali:/data/data/tools/WebCrack# python3 webcrack.py

*****************************************************
*                                                   *
****************    Code By yzddMr6   ***************
*                                                   *
*****************************************************

File or Url:
url.txt
url.txt exists!

总任务数: 2

[1/2]  url: https://www.ymadao.com/wp-login.php

[2/2]  url: https://www.zmymk.com/wp-login.php?redirect_to=https%3A%2F%2Fwww.zmymk.com%2Fwp-admin%2F&reauth=1

就是这样的。。。

**Comment by yzddmr6** [comment]
没识别出来wordpress的登录框，已知问题，下个版本改。
