### ISSUE TITLE
大佬，麻烦看下报错

### ISSUE THREAD

**Issue by B0luo** [yzddmr6/WebCrack#15]
一直报错Parse Error: 'action'
![1](https://user-images.githubusercontent.com/25783313/124878722-034d8a80-dfff-11eb-914f-ad9ce71d45f2.jpg)

**Comment by yzddmr6** [comment]
看起来是没有找到action字段，方便的话把登录框源码贴一下吧

**Comment by yzddmr6** [comment]
已更新
