### ISSUE TITLE
大佬，登录页面的form表单没有 action 怎么解决呢？

### ISSUE THREAD

**Issue by moon-zhangyue** [yzddmr6/WebCrack#3]
Checking : http://baisha.local/ 2020-03-27 16:18:58
2020-03-27 16:18:58.953513 'action'

我自测的地址  提交表单没有action 该怎么操作呢

**Comment by yzddmr6** [comment]
忘了考虑action字段为空或者没有action的情况，下个版本改一下

**Comment by moon-zhangyue** [comment]
OK
