### ISSUE TITLE
运行报错（不是代码问题吧）

### ISSUE THREAD

**Issue by AveryJiang** [yzddmr6/WebCrack#7]
运行python3 WebCrack.py时
报错：
Traceback (most recent call last):
  File "/Users/averyjiang/WebCrack/webcrack.py", line 8, in <module>
    import time, requests, os, sys, re
ModuleNotFoundError: No module named 'requests'

**Comment by AveryJiang** [comment]
额大佬能给os用户优化优化吗？

**Comment by yzddmr6** [comment]
pip install requests
