### ISSUE TITLE
关于样本的问题

### ISSUE THREAD

**Issue by mengmeizhi** [yzddmr6/WebCrack#8]
你好，我最近在也在做扫描器爆破模块，想问下关于爆破样本有比较好的获取途径吗

**Comment by warmilk** [comment]
同求样本获取途径。我目前是通过Google hack去手动搜索 inurl: admin.asp 的结果将url复制粘贴到url.txt内

**Comment by warmilk** [comment]
另外不明白为啥要屏蔽 .edu 和 .gov 的域名呢？我是小白，望解答

**Comment by yzddmr6** [comment]
1. 爬虫
2. 扫描
3. 自己搭建一些CMS
好像也没有什么太好的办法
